name: Баг
description: Нашли недоработки в игре? Сообщите о них мне.
title: "Title"
labels: [Баг]
body:
  - type: textarea
    id: description
    attributes:
      label: "Опишите что это за баг и когда он появляется."
    validations:
      required: true
  - type: checkboxes
    id: confirmation
    attributes:
      label: Перед тем как отправлять, вы должны подтвердить:
      options:
        - label: Я уверен что это баг
          required: true